[profile.release]
opt-level = 3

[profile.dev]
opt-level = 1

[package]
edition = "2021"
name = "creator"
version = "0.1.0"

[dependencies]
cursive = { version = "0.21", features = ["toml"] }
directories = "5.0.1"
log = "0.4"
regex = "1.9"
simplelog = "0.12.2"
walkdir = "2.5"
