name: Rust Check (Formatting, Clippy, and Linters)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: 'true'
          toolchain: stable

      - name: Run rustfmt
        run: |
          cargo fmt -- --check

      - name: Run Clippy
        run: |
          cargo clippy -- -D warnings

      - name: Run Tests
        run: |
          cargo test

      - name: Run cargo audit
        run: |
          cargo install cargo-audit
          cargo audit --deny=warnings
